"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scripts_list import ScriptsList


class TestScriptsList(unittest.TestCase):
    """ScriptsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScriptsList(self):
        """Test ScriptsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScriptsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
