"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.prompt_style_item import PromptStyleItem


class TestPromptStyleItem(unittest.TestCase):
    """PromptStyleItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPromptStyleItem(self):
        """Test PromptStyleItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PromptStyleItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
