"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.control_net_unit_request import ControlNetUnitRequest
globals()['ControlNetUnitRequest'] = ControlNetUnitRequest
from openapi_client.model.control_net_stable_diffusion_processing_img2_img import ControlNetStableDiffusionProcessingImg2Img


class TestControlNetStableDiffusionProcessingImg2Img(unittest.TestCase):
    """ControlNetStableDiffusionProcessingImg2Img unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testControlNetStableDiffusionProcessingImg2Img(self):
        """Test ControlNetStableDiffusionProcessingImg2Img"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ControlNetStableDiffusionProcessingImg2Img()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
