"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.train_response import TrainResponse


class TestTrainResponse(unittest.TestCase):
    """TrainResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainResponse(self):
        """Test TrainResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
