"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.embedding_item import EmbeddingItem


class TestEmbeddingItem(unittest.TestCase):
    """EmbeddingItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbeddingItem(self):
        """Test EmbeddingItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmbeddingItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
