"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_app_id_app_id_get(self):
        """Test case for app_id_app_id_get

        App Id  # noqa: E501
        """
        pass

    def test_app_id_app_id_get_0(self):
        """Test case for app_id_app_id_get_0

        App Id  # noqa: E501
        """
        pass

    def test_build_resource_assets_path_get(self):
        """Test case for build_resource_assets_path_get

        Build Resource  # noqa: E501
        """
        pass

    def test_controlnet_img2img_controlnet_img2img_post(self):
        """Test case for controlnet_img2img_controlnet_img2img_post

        Controlnet Img2Img  # noqa: E501
        """
        pass

    def test_controlnet_txt2img_controlnet_txt2img_post(self):
        """Test case for controlnet_txt2img_controlnet_txt2img_post

        Controlnet Txt2Img  # noqa: E501
        """
        pass

    def test_create_embedding_sdapi_v1_create_embedding_post(self):
        """Test case for create_embedding_sdapi_v1_create_embedding_post

        Create Embedding  # noqa: E501
        """
        pass

    def test_create_hypernetwork_sdapi_v1_create_hypernetwork_post(self):
        """Test case for create_hypernetwork_sdapi_v1_create_hypernetwork_post

        Create Hypernetwork  # noqa: E501
        """
        pass

    def test_extras_batch_images_api_sdapi_v1_extra_batch_images_post(self):
        """Test case for extras_batch_images_api_sdapi_v1_extra_batch_images_post

        Extras Batch Images Api  # noqa: E501
        """
        pass

    def test_extras_single_image_api_sdapi_v1_extra_single_image_post(self):
        """Test case for extras_single_image_api_sdapi_v1_extra_single_image_post

        Extras Single Image Api  # noqa: E501
        """
        pass

    def test_favicon_favicon_ico_get(self):
        """Test case for favicon_favicon_ico_get

        Favicon  # noqa: E501
        """
        pass

    def test_fetch_file_sd_extra_networks_thumb_get(self):
        """Test case for fetch_file_sd_extra_networks_thumb_get

        Fetch File  # noqa: E501
        """
        pass

    def test_file_deprecated_file_path_get(self):
        """Test case for file_deprecated_file_path_get

        File Deprecated  # noqa: E501
        """
        pass

    def test_file_file_path_or_url_get(self):
        """Test case for file_file_path_or_url_get

        File  # noqa: E501
        """
        pass

    def test_file_file_path_or_url_head(self):
        """Test case for file_file_path_or_url_head

        File  # noqa: E501
        """
        pass

    def test_get_cmd_flags_sdapi_v1_cmd_flags_get(self):
        """Test case for get_cmd_flags_sdapi_v1_cmd_flags_get

        Get Cmd Flags  # noqa: E501
        """
        pass

    def test_get_config_config_get(self):
        """Test case for get_config_config_get

        Get Config  # noqa: E501
        """
        pass

    def test_get_config_config_get_0(self):
        """Test case for get_config_config_get_0

        Get Config  # noqa: E501
        """
        pass

    def test_get_config_sdapi_v1_options_get(self):
        """Test case for get_config_sdapi_v1_options_get

        Get Config  # noqa: E501
        """
        pass

    def test_get_current_user_user_get(self):
        """Test case for get_current_user_user_get

        Get Current User  # noqa: E501
        """
        pass

    def test_get_current_user_user_get_0(self):
        """Test case for get_current_user_user_get_0

        Get Current User  # noqa: E501
        """
        pass

    def test_get_embeddings_sdapi_v1_embeddings_get(self):
        """Test case for get_embeddings_sdapi_v1_embeddings_get

        Get Embeddings  # noqa: E501
        """
        pass

    def test_get_face_restorers_sdapi_v1_face_restorers_get(self):
        """Test case for get_face_restorers_sdapi_v1_face_restorers_get

        Get Face Restorers  # noqa: E501
        """
        pass

    def test_get_hypernetworks_sdapi_v1_hypernetworks_get(self):
        """Test case for get_hypernetworks_sdapi_v1_hypernetworks_get

        Get Hypernetworks  # noqa: E501
        """
        pass

    def test_get_info_import_info_get(self):
        """Test case for get_info_import_info_get

        Get Info  # noqa: E501
        """
        pass

    def test_get_memory_sdapi_v1_memory_get(self):
        """Test case for get_memory_sdapi_v1_memory_get

        Get Memory  # noqa: E501
        """
        pass

    def test_get_metadata_sd_extra_networks_metadata_get(self):
        """Test case for get_metadata_sd_extra_networks_metadata_get

        Get Metadata  # noqa: E501
        """
        pass

    def test_get_prompt_styles_sdapi_v1_prompt_styles_get(self):
        """Test case for get_prompt_styles_sdapi_v1_prompt_styles_get

        Get Prompt Styles  # noqa: E501
        """
        pass

    def test_get_queue_status_queue_status_get(self):
        """Test case for get_queue_status_queue_status_get

        Get Queue Status  # noqa: E501
        """
        pass

    def test_get_realesrgan_models_sdapi_v1_realesrgan_models_get(self):
        """Test case for get_realesrgan_models_sdapi_v1_realesrgan_models_get

        Get Realesrgan Models  # noqa: E501
        """
        pass

    def test_get_samplers_sdapi_v1_samplers_get(self):
        """Test case for get_samplers_sdapi_v1_samplers_get

        Get Samplers  # noqa: E501
        """
        pass

    def test_get_scripts_list_sdapi_v1_scripts_get(self):
        """Test case for get_scripts_list_sdapi_v1_scripts_get

        Get Scripts List  # noqa: E501
        """
        pass

    def test_get_sd_models_sdapi_v1_sd_models_get(self):
        """Test case for get_sd_models_sdapi_v1_sd_models_get

        Get Sd Models  # noqa: E501
        """
        pass

    def test_get_token_token_get(self):
        """Test case for get_token_token_get

        Get Token  # noqa: E501
        """
        pass

    def test_get_token_token_get_0(self):
        """Test case for get_token_token_get_0

        Get Token  # noqa: E501
        """
        pass

    def test_get_upscalers_sdapi_v1_upscalers_get(self):
        """Test case for get_upscalers_sdapi_v1_upscalers_get

        Get Upscalers  # noqa: E501
        """
        pass

    def test_get_wstest_get(self):
        """Test case for get_wstest_get

        Get  # noqa: E501
        """
        pass

    def test_img2imgapi_sdapi_v1_img2img_post(self):
        """Test case for img2imgapi_sdapi_v1_img2img_post

        Img2Imgapi  # noqa: E501
        """
        pass

    def test_interrogateapi_sdapi_v1_interrogate_post(self):
        """Test case for interrogateapi_sdapi_v1_interrogate_post

        Interrogateapi  # noqa: E501
        """
        pass

    def test_interruptapi_sdapi_v1_interrupt_post(self):
        """Test case for interruptapi_sdapi_v1_interrupt_post

        Interruptapi  # noqa: E501
        """
        pass

    def test_login_check_login_check_get(self):
        """Test case for login_check_login_check_get

        Login Check  # noqa: E501
        """
        pass

    def test_login_check_login_check_get_0(self):
        """Test case for login_check_login_check_get_0

        Login Check  # noqa: E501
        """
        pass

    def test_login_login_post(self):
        """Test case for login_login_post

        Login  # noqa: E501
        """
        pass

    def test_login_login_post_0(self):
        """Test case for login_login_post_0

        Login  # noqa: E501
        """
        pass

    def test_main_get(self):
        """Test case for main_get

        Main  # noqa: E501
        """
        pass

    def test_main_head(self):
        """Test case for main_head

        Main  # noqa: E501
        """
        pass

    def test_pnginfoapi_sdapi_v1_png_info_post(self):
        """Test case for pnginfoapi_sdapi_v1_png_info_post

        Pnginfoapi  # noqa: E501
        """
        pass

    def test_predict_api_api_name_post(self):
        """Test case for predict_api_api_name_post

        Predict  # noqa: E501
        """
        pass

    def test_predict_api_api_name_post_0(self):
        """Test case for predict_api_api_name_post_0

        Predict  # noqa: E501
        """
        pass

    def test_predict_run_api_name_post(self):
        """Test case for predict_run_api_name_post

        Predict  # noqa: E501
        """
        pass

    def test_predict_run_api_name_post_0(self):
        """Test case for predict_run_api_name_post_0

        Predict  # noqa: E501
        """
        pass

    def test_preprocess_sdapi_v1_preprocess_post(self):
        """Test case for preprocess_sdapi_v1_preprocess_post

        Preprocess  # noqa: E501
        """
        pass

    def test_progressapi_internal_progress_post(self):
        """Test case for progressapi_internal_progress_post

        Progressapi  # noqa: E501
        """
        pass

    def test_progressapi_sdapi_v1_progress_get(self):
        """Test case for progressapi_sdapi_v1_progress_get

        Progressapi  # noqa: E501
        """
        pass

    def test_refresh_checkpoints_sdapi_v1_refresh_checkpoints_post(self):
        """Test case for refresh_checkpoints_sdapi_v1_refresh_checkpoints_post

        Refresh Checkpoints  # noqa: E501
        """
        pass

    def test_reloadapi_sdapi_v1_reload_checkpoint_post(self):
        """Test case for reloadapi_sdapi_v1_reload_checkpoint_post

        Reloadapi  # noqa: E501
        """
        pass

    def test_reset_iterator_reset_post(self):
        """Test case for reset_iterator_reset_post

        Reset Iterator  # noqa: E501
        """
        pass

    def test_reset_iterator_reset_post_0(self):
        """Test case for reset_iterator_reset_post_0

        Reset Iterator  # noqa: E501
        """
        pass

    def test_reverse_proxy_proxy_url_path_get(self):
        """Test case for reverse_proxy_proxy_url_path_get

        Reverse Proxy  # noqa: E501
        """
        pass

    def test_reverse_proxy_proxy_url_path_head(self):
        """Test case for reverse_proxy_proxy_url_path_head

        Reverse Proxy  # noqa: E501
        """
        pass

    def test_robots_txt_robots_txt_get(self):
        """Test case for robots_txt_robots_txt_get

        Robots Txt  # noqa: E501
        """
        pass

    def test_set_config_sdapi_v1_options_post(self):
        """Test case for set_config_sdapi_v1_options_post

        Set Config  # noqa: E501
        """
        pass

    def test_skip_login_api_skip_login_api_get(self):
        """Test case for skip_login_api_skip_login_api_get

        Skip Login Api  # noqa: E501
        """
        pass

    def test_skip_login_api_skip_login_api_get_0(self):
        """Test case for skip_login_api_skip_login_api_get_0

        Skip Login Api  # noqa: E501
        """
        pass

    def test_skip_login_skip_login_get(self):
        """Test case for skip_login_skip_login_get

        Skip Login  # noqa: E501
        """
        pass

    def test_skip_login_skip_login_get_0(self):
        """Test case for skip_login_skip_login_get_0

        Skip Login  # noqa: E501
        """
        pass

    def test_skip_sdapi_v1_skip_post(self):
        """Test case for skip_sdapi_v1_skip_post

        Skip  # noqa: E501
        """
        pass

    def test_startup_events_startup_events_get(self):
        """Test case for startup_events_startup_events_get

        Startup Events  # noqa: E501
        """
        pass

    def test_static_resource_static_path_get(self):
        """Test case for static_resource_static_path_get

        Static Resource  # noqa: E501
        """
        pass

    def test_text2imgapi_sdapi_v1_txt2img_post(self):
        """Test case for text2imgapi_sdapi_v1_txt2img_post

        Text2Imgapi  # noqa: E501
        """
        pass

    def test_theme_css_theme_css_get(self):
        """Test case for theme_css_theme_css_get

        Theme Css  # noqa: E501
        """
        pass

    def test_train_embedding_sdapi_v1_train_embedding_post(self):
        """Test case for train_embedding_sdapi_v1_train_embedding_post

        Train Embedding  # noqa: E501
        """
        pass

    def test_train_hypernetwork_sdapi_v1_train_hypernetwork_post(self):
        """Test case for train_hypernetwork_sdapi_v1_train_hypernetwork_post

        Train Hypernetwork  # noqa: E501
        """
        pass

    def test_unloadapi_sdapi_v1_unload_checkpoint_post(self):
        """Test case for unloadapi_sdapi_v1_unload_checkpoint_post

        Unloadapi  # noqa: E501
        """
        pass

    def test_upload_file_upload_post(self):
        """Test case for upload_file_upload_post

        Upload File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
