"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError



class ExtrasSingleImageRequest(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('resize_mode',): {
            '0': 0,
            '1': 1,
        },
    }

    validations = {
        ('gfpgan_visibility',): {
            'inclusive_maximum': 1.0,
            'inclusive_minimum': 0.0,
        },
        ('codeformer_visibility',): {
            'inclusive_maximum': 1.0,
            'inclusive_minimum': 0.0,
        },
        ('codeformer_weight',): {
            'inclusive_maximum': 1.0,
            'inclusive_minimum': 0.0,
        },
        ('upscaling_resize',): {
            'inclusive_maximum': 8.0,
            'inclusive_minimum': 1.0,
        },
        ('upscaling_resize_w',): {
            'inclusive_minimum': 1,
        },
        ('upscaling_resize_h',): {
            'inclusive_minimum': 1,
        },
        ('extras_upscaler_2_visibility',): {
            'inclusive_maximum': 1.0,
            'inclusive_minimum': 0.0,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'resize_mode': (int,),  # noqa: E501
            'show_extras_results': (bool,),  # noqa: E501
            'gfpgan_visibility': (float,),  # noqa: E501
            'codeformer_visibility': (float,),  # noqa: E501
            'codeformer_weight': (float,),  # noqa: E501
            'upscaling_resize': (float,),  # noqa: E501
            'upscaling_resize_w': (int,),  # noqa: E501
            'upscaling_resize_h': (int,),  # noqa: E501
            'upscaling_crop': (bool,),  # noqa: E501
            'upscaler_1': (str,),  # noqa: E501
            'upscaler_2': (str,),  # noqa: E501
            'extras_upscaler_2_visibility': (float,),  # noqa: E501
            'upscale_first': (bool,),  # noqa: E501
            'image': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'resize_mode': 'resize_mode',  # noqa: E501
        'show_extras_results': 'show_extras_results',  # noqa: E501
        'gfpgan_visibility': 'gfpgan_visibility',  # noqa: E501
        'codeformer_visibility': 'codeformer_visibility',  # noqa: E501
        'codeformer_weight': 'codeformer_weight',  # noqa: E501
        'upscaling_resize': 'upscaling_resize',  # noqa: E501
        'upscaling_resize_w': 'upscaling_resize_w',  # noqa: E501
        'upscaling_resize_h': 'upscaling_resize_h',  # noqa: E501
        'upscaling_crop': 'upscaling_crop',  # noqa: E501
        'upscaler_1': 'upscaler_1',  # noqa: E501
        'upscaler_2': 'upscaler_2',  # noqa: E501
        'extras_upscaler_2_visibility': 'extras_upscaler_2_visibility',  # noqa: E501
        'upscale_first': 'upscale_first',  # noqa: E501
        'image': 'image',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ExtrasSingleImageRequest - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            resize_mode (int): Sets the resize mode: 0 to upscale by upscaling_resize amount, 1 to upscale up to upscaling_resize_h x upscaling_resize_w.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            show_extras_results (bool): Should the backend return the generated image?. [optional] if omitted the server will use the default value of True  # noqa: E501
            gfpgan_visibility (float): Sets the visibility of GFPGAN, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            codeformer_visibility (float): Sets the visibility of CodeFormer, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            codeformer_weight (float): Sets the weight of CodeFormer, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            upscaling_resize (float): By how much to upscale the image, only used when resize_mode=0.. [optional] if omitted the server will use the default value of 2  # noqa: E501
            upscaling_resize_w (int): Target width for the upscaler to hit. Only used when resize_mode=1.. [optional] if omitted the server will use the default value of 512  # noqa: E501
            upscaling_resize_h (int): Target height for the upscaler to hit. Only used when resize_mode=1.. [optional] if omitted the server will use the default value of 512  # noqa: E501
            upscaling_crop (bool): Should the upscaler crop the image to fit in the chosen size?. [optional] if omitted the server will use the default value of True  # noqa: E501
            upscaler_1 (str): The name of the main upscaler to use, it has to be one of this list: None , Lanczos , Nearest , R-ESRGAN 4x+ , R-ESRGAN 4x+ Anime6B , RRDB_ESRGAN_x4. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            upscaler_2 (str): The name of the secondary upscaler to use, it has to be one of this list: None , Lanczos , Nearest , R-ESRGAN 4x+ , R-ESRGAN 4x+ Anime6B , RRDB_ESRGAN_x4. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            extras_upscaler_2_visibility (float): Sets the visibility of secondary upscaler, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            upscale_first (bool): Should the upscaler run before restoring faces?. [optional] if omitted the server will use the default value of False  # noqa: E501
            image (str): Image to work on, must be a Base64 string containing the image's data.. [optional] if omitted the server will use the default value of ""  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ExtrasSingleImageRequest - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            resize_mode (int): Sets the resize mode: 0 to upscale by upscaling_resize amount, 1 to upscale up to upscaling_resize_h x upscaling_resize_w.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            show_extras_results (bool): Should the backend return the generated image?. [optional] if omitted the server will use the default value of True  # noqa: E501
            gfpgan_visibility (float): Sets the visibility of GFPGAN, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            codeformer_visibility (float): Sets the visibility of CodeFormer, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            codeformer_weight (float): Sets the weight of CodeFormer, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            upscaling_resize (float): By how much to upscale the image, only used when resize_mode=0.. [optional] if omitted the server will use the default value of 2  # noqa: E501
            upscaling_resize_w (int): Target width for the upscaler to hit. Only used when resize_mode=1.. [optional] if omitted the server will use the default value of 512  # noqa: E501
            upscaling_resize_h (int): Target height for the upscaler to hit. Only used when resize_mode=1.. [optional] if omitted the server will use the default value of 512  # noqa: E501
            upscaling_crop (bool): Should the upscaler crop the image to fit in the chosen size?. [optional] if omitted the server will use the default value of True  # noqa: E501
            upscaler_1 (str): The name of the main upscaler to use, it has to be one of this list: None , Lanczos , Nearest , R-ESRGAN 4x+ , R-ESRGAN 4x+ Anime6B , RRDB_ESRGAN_x4. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            upscaler_2 (str): The name of the secondary upscaler to use, it has to be one of this list: None , Lanczos , Nearest , R-ESRGAN 4x+ , R-ESRGAN 4x+ Anime6B , RRDB_ESRGAN_x4. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            extras_upscaler_2_visibility (float): Sets the visibility of secondary upscaler, values should be between 0 and 1.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            upscale_first (bool): Should the upscaler run before restoring faces?. [optional] if omitted the server will use the default value of False  # noqa: E501
            image (str): Image to work on, must be a Base64 string containing the image's data.. [optional] if omitted the server will use the default value of ""  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
