"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError



class Options(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'samples_save': (bool,),  # noqa: E501
            'samples_format': (str,),  # noqa: E501
            'samples_filename_pattern': (str,),  # noqa: E501
            'save_images_add_number': (bool,),  # noqa: E501
            'grid_save': (bool,),  # noqa: E501
            'grid_format': (str,),  # noqa: E501
            'grid_extended_filename': (bool,),  # noqa: E501
            'grid_only_if_multiple': (bool,),  # noqa: E501
            'grid_prevent_empty_spots': (bool,),  # noqa: E501
            'n_rows': (float,),  # noqa: E501
            'enable_pnginfo': (bool,),  # noqa: E501
            'save_txt': (bool,),  # noqa: E501
            'save_images_before_face_restoration': (bool,),  # noqa: E501
            'save_images_before_highres_fix': (bool,),  # noqa: E501
            'save_images_before_color_correction': (bool,),  # noqa: E501
            'save_mask': (bool,),  # noqa: E501
            'save_mask_composite': (bool,),  # noqa: E501
            'jpeg_quality': (float,),  # noqa: E501
            'webp_lossless': (bool,),  # noqa: E501
            'export_for_4chan': (bool,),  # noqa: E501
            'img_downscale_threshold': (float,),  # noqa: E501
            'target_side_length': (float,),  # noqa: E501
            'img_max_size_mp': (float,),  # noqa: E501
            'use_original_name_batch': (bool,),  # noqa: E501
            'use_upscaler_name_as_suffix': (bool,),  # noqa: E501
            'save_selected_only': (bool,),  # noqa: E501
            'do_not_add_watermark': (bool,),  # noqa: E501
            'temp_dir': (str,),  # noqa: E501
            'clean_temp_dir_at_start': (bool,),  # noqa: E501
            'outdir_samples': (str,),  # noqa: E501
            'outdir_txt2img_samples': (str,),  # noqa: E501
            'outdir_img2img_samples': (str,),  # noqa: E501
            'outdir_extras_samples': (str,),  # noqa: E501
            'outdir_grids': (str,),  # noqa: E501
            'outdir_txt2img_grids': (str,),  # noqa: E501
            'outdir_img2img_grids': (str,),  # noqa: E501
            'outdir_save': (str,),  # noqa: E501
            'save_to_dirs': (bool,),  # noqa: E501
            'grid_save_to_dirs': (bool,),  # noqa: E501
            'use_save_to_dirs_for_ui': (bool,),  # noqa: E501
            'directories_filename_pattern': (str,),  # noqa: E501
            'directories_max_prompt_words': (float,),  # noqa: E501
            'esrgan_tile': (float,),  # noqa: E501
            'esrgan_tile_overlap': (float,),  # noqa: E501
            'realesrgan_enabled_models': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'upscaler_for_img2img': (none_type,),  # noqa: E501
            'face_restoration_model': (str,),  # noqa: E501
            'code_former_weight': (float,),  # noqa: E501
            'face_restoration_unload': (bool,),  # noqa: E501
            'show_warnings': (bool,),  # noqa: E501
            'memmon_poll_rate': (float,),  # noqa: E501
            'samples_log_stdout': (bool,),  # noqa: E501
            'multiple_tqdm': (bool,),  # noqa: E501
            'print_hypernet_extra': (bool,),  # noqa: E501
            'unload_models_when_training': (bool,),  # noqa: E501
            'pin_memory': (bool,),  # noqa: E501
            'save_optimizer_state': (bool,),  # noqa: E501
            'save_training_settings_to_txt': (bool,),  # noqa: E501
            'dataset_filename_word_regex': (str,),  # noqa: E501
            'dataset_filename_join_string': (str,),  # noqa: E501
            'training_image_repeats_per_epoch': (float,),  # noqa: E501
            'training_write_csv_every': (float,),  # noqa: E501
            'training_xattention_optimizations': (bool,),  # noqa: E501
            'training_enable_tensorboard': (bool,),  # noqa: E501
            'training_tensorboard_save_images': (bool,),  # noqa: E501
            'training_tensorboard_flush_every': (float,),  # noqa: E501
            'sd_model_checkpoint': (str,),  # noqa: E501
            'sd_checkpoint_cache': (float,),  # noqa: E501
            'sd_vae_checkpoint_cache': (float,),  # noqa: E501
            'sd_vae': (str,),  # noqa: E501
            'sd_vae_as_default': (bool,),  # noqa: E501
            'inpainting_mask_weight': (float,),  # noqa: E501
            'initial_noise_multiplier': (float,),  # noqa: E501
            'img2img_color_correction': (bool,),  # noqa: E501
            'img2img_fix_steps': (bool,),  # noqa: E501
            'img2img_background_color': (str,),  # noqa: E501
            'enable_quantization': (bool,),  # noqa: E501
            'enable_emphasis': (bool,),  # noqa: E501
            'enable_batch_seeds': (bool,),  # noqa: E501
            'comma_padding_backtrack': (float,),  # noqa: E501
            'clip_stop_at_last_layers': (float,),  # noqa: E501
            'upcast_attn': (bool,),  # noqa: E501
            'use_old_emphasis_implementation': (bool,),  # noqa: E501
            'use_old_karras_scheduler_sigmas': (bool,),  # noqa: E501
            'no_dpmpp_sde_batch_determinism': (bool,),  # noqa: E501
            'use_old_hires_fix_width_height': (bool,),  # noqa: E501
            'interrogate_keep_models_in_memory': (bool,),  # noqa: E501
            'interrogate_return_ranks': (bool,),  # noqa: E501
            'interrogate_clip_num_beams': (float,),  # noqa: E501
            'interrogate_clip_min_length': (float,),  # noqa: E501
            'interrogate_clip_max_length': (float,),  # noqa: E501
            'interrogate_clip_dict_limit': (float,),  # noqa: E501
            'interrogate_clip_skip_categories': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'interrogate_deepbooru_score_threshold': (float,),  # noqa: E501
            'deepbooru_sort_alpha': (bool,),  # noqa: E501
            'deepbooru_use_spaces': (bool,),  # noqa: E501
            'deepbooru_escape': (bool,),  # noqa: E501
            'deepbooru_filter_tags': (str,),  # noqa: E501
            'extra_networks_default_view': (str,),  # noqa: E501
            'extra_networks_default_multiplier': (float,),  # noqa: E501
            'extra_networks_card_width': (float,),  # noqa: E501
            'extra_networks_card_height': (float,),  # noqa: E501
            'extra_networks_add_text_separator': (str,),  # noqa: E501
            'sd_hypernetwork': (str,),  # noqa: E501
            'return_grid': (bool,),  # noqa: E501
            'return_mask': (bool,),  # noqa: E501
            'return_mask_composite': (bool,),  # noqa: E501
            'do_not_show_images': (bool,),  # noqa: E501
            'add_model_hash_to_info': (bool,),  # noqa: E501
            'add_model_name_to_info': (bool,),  # noqa: E501
            'disable_weights_auto_swap': (bool,),  # noqa: E501
            'send_seed': (bool,),  # noqa: E501
            'send_size': (bool,),  # noqa: E501
            'font': (str,),  # noqa: E501
            'js_modal_lightbox': (bool,),  # noqa: E501
            'js_modal_lightbox_initially_zoomed': (bool,),  # noqa: E501
            'show_progress_in_title': (bool,),  # noqa: E501
            'samplers_in_dropdown': (bool,),  # noqa: E501
            'dimensions_and_batch_together': (bool,),  # noqa: E501
            'keyedit_precision_attention': (float,),  # noqa: E501
            'keyedit_precision_extra': (float,),  # noqa: E501
            'quicksettings': (str,),  # noqa: E501
            'hidden_tabs': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'ui_reorder': (str,),  # noqa: E501
            'ui_extra_networks_tab_reorder': (str,),  # noqa: E501
            'localization': (str,),  # noqa: E501
            'show_progressbar': (bool,),  # noqa: E501
            'live_previews_enable': (bool,),  # noqa: E501
            'show_progress_grid': (bool,),  # noqa: E501
            'show_progress_every_n_steps': (float,),  # noqa: E501
            'show_progress_type': (str,),  # noqa: E501
            'live_preview_content': (str,),  # noqa: E501
            'live_preview_refresh_period': (float,),  # noqa: E501
            'hide_samplers': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'eta_ddim': (float,),  # noqa: E501
            'eta_ancestral': (float,),  # noqa: E501
            'ddim_discretize': (str,),  # noqa: E501
            's_churn': (float,),  # noqa: E501
            's_tmin': (float,),  # noqa: E501
            's_noise': (float,),  # noqa: E501
            'eta_noise_seed_delta': (float,),  # noqa: E501
            'always_discard_next_to_last_sigma': (bool,),  # noqa: E501
            'uni_pc_variant': (str,),  # noqa: E501
            'uni_pc_skip_type': (str,),  # noqa: E501
            'uni_pc_order': (float,),  # noqa: E501
            'uni_pc_lower_order_final': (bool,),  # noqa: E501
            'postprocessing_enable_in_main_ui': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'postprocessing_operation_order': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'upscaling_max_images_in_cache': (float,),  # noqa: E501
            'disabled_extensions': ([bool, date, datetime, dict, float, int, list, str, none_type],),  # noqa: E501
            'disable_all_extensions': (str,),  # noqa: E501
            'sd_checkpoint_hash': (str,),  # noqa: E501
            'sd_lyco': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'samples_save': 'samples_save',  # noqa: E501
        'samples_format': 'samples_format',  # noqa: E501
        'samples_filename_pattern': 'samples_filename_pattern',  # noqa: E501
        'save_images_add_number': 'save_images_add_number',  # noqa: E501
        'grid_save': 'grid_save',  # noqa: E501
        'grid_format': 'grid_format',  # noqa: E501
        'grid_extended_filename': 'grid_extended_filename',  # noqa: E501
        'grid_only_if_multiple': 'grid_only_if_multiple',  # noqa: E501
        'grid_prevent_empty_spots': 'grid_prevent_empty_spots',  # noqa: E501
        'n_rows': 'n_rows',  # noqa: E501
        'enable_pnginfo': 'enable_pnginfo',  # noqa: E501
        'save_txt': 'save_txt',  # noqa: E501
        'save_images_before_face_restoration': 'save_images_before_face_restoration',  # noqa: E501
        'save_images_before_highres_fix': 'save_images_before_highres_fix',  # noqa: E501
        'save_images_before_color_correction': 'save_images_before_color_correction',  # noqa: E501
        'save_mask': 'save_mask',  # noqa: E501
        'save_mask_composite': 'save_mask_composite',  # noqa: E501
        'jpeg_quality': 'jpeg_quality',  # noqa: E501
        'webp_lossless': 'webp_lossless',  # noqa: E501
        'export_for_4chan': 'export_for_4chan',  # noqa: E501
        'img_downscale_threshold': 'img_downscale_threshold',  # noqa: E501
        'target_side_length': 'target_side_length',  # noqa: E501
        'img_max_size_mp': 'img_max_size_mp',  # noqa: E501
        'use_original_name_batch': 'use_original_name_batch',  # noqa: E501
        'use_upscaler_name_as_suffix': 'use_upscaler_name_as_suffix',  # noqa: E501
        'save_selected_only': 'save_selected_only',  # noqa: E501
        'do_not_add_watermark': 'do_not_add_watermark',  # noqa: E501
        'temp_dir': 'temp_dir',  # noqa: E501
        'clean_temp_dir_at_start': 'clean_temp_dir_at_start',  # noqa: E501
        'outdir_samples': 'outdir_samples',  # noqa: E501
        'outdir_txt2img_samples': 'outdir_txt2img_samples',  # noqa: E501
        'outdir_img2img_samples': 'outdir_img2img_samples',  # noqa: E501
        'outdir_extras_samples': 'outdir_extras_samples',  # noqa: E501
        'outdir_grids': 'outdir_grids',  # noqa: E501
        'outdir_txt2img_grids': 'outdir_txt2img_grids',  # noqa: E501
        'outdir_img2img_grids': 'outdir_img2img_grids',  # noqa: E501
        'outdir_save': 'outdir_save',  # noqa: E501
        'save_to_dirs': 'save_to_dirs',  # noqa: E501
        'grid_save_to_dirs': 'grid_save_to_dirs',  # noqa: E501
        'use_save_to_dirs_for_ui': 'use_save_to_dirs_for_ui',  # noqa: E501
        'directories_filename_pattern': 'directories_filename_pattern',  # noqa: E501
        'directories_max_prompt_words': 'directories_max_prompt_words',  # noqa: E501
        'esrgan_tile': 'ESRGAN_tile',  # noqa: E501
        'esrgan_tile_overlap': 'ESRGAN_tile_overlap',  # noqa: E501
        'realesrgan_enabled_models': 'realesrgan_enabled_models',  # noqa: E501
        'upscaler_for_img2img': 'upscaler_for_img2img',  # noqa: E501
        'face_restoration_model': 'face_restoration_model',  # noqa: E501
        'code_former_weight': 'code_former_weight',  # noqa: E501
        'face_restoration_unload': 'face_restoration_unload',  # noqa: E501
        'show_warnings': 'show_warnings',  # noqa: E501
        'memmon_poll_rate': 'memmon_poll_rate',  # noqa: E501
        'samples_log_stdout': 'samples_log_stdout',  # noqa: E501
        'multiple_tqdm': 'multiple_tqdm',  # noqa: E501
        'print_hypernet_extra': 'print_hypernet_extra',  # noqa: E501
        'unload_models_when_training': 'unload_models_when_training',  # noqa: E501
        'pin_memory': 'pin_memory',  # noqa: E501
        'save_optimizer_state': 'save_optimizer_state',  # noqa: E501
        'save_training_settings_to_txt': 'save_training_settings_to_txt',  # noqa: E501
        'dataset_filename_word_regex': 'dataset_filename_word_regex',  # noqa: E501
        'dataset_filename_join_string': 'dataset_filename_join_string',  # noqa: E501
        'training_image_repeats_per_epoch': 'training_image_repeats_per_epoch',  # noqa: E501
        'training_write_csv_every': 'training_write_csv_every',  # noqa: E501
        'training_xattention_optimizations': 'training_xattention_optimizations',  # noqa: E501
        'training_enable_tensorboard': 'training_enable_tensorboard',  # noqa: E501
        'training_tensorboard_save_images': 'training_tensorboard_save_images',  # noqa: E501
        'training_tensorboard_flush_every': 'training_tensorboard_flush_every',  # noqa: E501
        'sd_model_checkpoint': 'sd_model_checkpoint',  # noqa: E501
        'sd_checkpoint_cache': 'sd_checkpoint_cache',  # noqa: E501
        'sd_vae_checkpoint_cache': 'sd_vae_checkpoint_cache',  # noqa: E501
        'sd_vae': 'sd_vae',  # noqa: E501
        'sd_vae_as_default': 'sd_vae_as_default',  # noqa: E501
        'inpainting_mask_weight': 'inpainting_mask_weight',  # noqa: E501
        'initial_noise_multiplier': 'initial_noise_multiplier',  # noqa: E501
        'img2img_color_correction': 'img2img_color_correction',  # noqa: E501
        'img2img_fix_steps': 'img2img_fix_steps',  # noqa: E501
        'img2img_background_color': 'img2img_background_color',  # noqa: E501
        'enable_quantization': 'enable_quantization',  # noqa: E501
        'enable_emphasis': 'enable_emphasis',  # noqa: E501
        'enable_batch_seeds': 'enable_batch_seeds',  # noqa: E501
        'comma_padding_backtrack': 'comma_padding_backtrack',  # noqa: E501
        'clip_stop_at_last_layers': 'CLIP_stop_at_last_layers',  # noqa: E501
        'upcast_attn': 'upcast_attn',  # noqa: E501
        'use_old_emphasis_implementation': 'use_old_emphasis_implementation',  # noqa: E501
        'use_old_karras_scheduler_sigmas': 'use_old_karras_scheduler_sigmas',  # noqa: E501
        'no_dpmpp_sde_batch_determinism': 'no_dpmpp_sde_batch_determinism',  # noqa: E501
        'use_old_hires_fix_width_height': 'use_old_hires_fix_width_height',  # noqa: E501
        'interrogate_keep_models_in_memory': 'interrogate_keep_models_in_memory',  # noqa: E501
        'interrogate_return_ranks': 'interrogate_return_ranks',  # noqa: E501
        'interrogate_clip_num_beams': 'interrogate_clip_num_beams',  # noqa: E501
        'interrogate_clip_min_length': 'interrogate_clip_min_length',  # noqa: E501
        'interrogate_clip_max_length': 'interrogate_clip_max_length',  # noqa: E501
        'interrogate_clip_dict_limit': 'interrogate_clip_dict_limit',  # noqa: E501
        'interrogate_clip_skip_categories': 'interrogate_clip_skip_categories',  # noqa: E501
        'interrogate_deepbooru_score_threshold': 'interrogate_deepbooru_score_threshold',  # noqa: E501
        'deepbooru_sort_alpha': 'deepbooru_sort_alpha',  # noqa: E501
        'deepbooru_use_spaces': 'deepbooru_use_spaces',  # noqa: E501
        'deepbooru_escape': 'deepbooru_escape',  # noqa: E501
        'deepbooru_filter_tags': 'deepbooru_filter_tags',  # noqa: E501
        'extra_networks_default_view': 'extra_networks_default_view',  # noqa: E501
        'extra_networks_default_multiplier': 'extra_networks_default_multiplier',  # noqa: E501
        'extra_networks_card_width': 'extra_networks_card_width',  # noqa: E501
        'extra_networks_card_height': 'extra_networks_card_height',  # noqa: E501
        'extra_networks_add_text_separator': 'extra_networks_add_text_separator',  # noqa: E501
        'sd_hypernetwork': 'sd_hypernetwork',  # noqa: E501
        'return_grid': 'return_grid',  # noqa: E501
        'return_mask': 'return_mask',  # noqa: E501
        'return_mask_composite': 'return_mask_composite',  # noqa: E501
        'do_not_show_images': 'do_not_show_images',  # noqa: E501
        'add_model_hash_to_info': 'add_model_hash_to_info',  # noqa: E501
        'add_model_name_to_info': 'add_model_name_to_info',  # noqa: E501
        'disable_weights_auto_swap': 'disable_weights_auto_swap',  # noqa: E501
        'send_seed': 'send_seed',  # noqa: E501
        'send_size': 'send_size',  # noqa: E501
        'font': 'font',  # noqa: E501
        'js_modal_lightbox': 'js_modal_lightbox',  # noqa: E501
        'js_modal_lightbox_initially_zoomed': 'js_modal_lightbox_initially_zoomed',  # noqa: E501
        'show_progress_in_title': 'show_progress_in_title',  # noqa: E501
        'samplers_in_dropdown': 'samplers_in_dropdown',  # noqa: E501
        'dimensions_and_batch_together': 'dimensions_and_batch_together',  # noqa: E501
        'keyedit_precision_attention': 'keyedit_precision_attention',  # noqa: E501
        'keyedit_precision_extra': 'keyedit_precision_extra',  # noqa: E501
        'quicksettings': 'quicksettings',  # noqa: E501
        'hidden_tabs': 'hidden_tabs',  # noqa: E501
        'ui_reorder': 'ui_reorder',  # noqa: E501
        'ui_extra_networks_tab_reorder': 'ui_extra_networks_tab_reorder',  # noqa: E501
        'localization': 'localization',  # noqa: E501
        'show_progressbar': 'show_progressbar',  # noqa: E501
        'live_previews_enable': 'live_previews_enable',  # noqa: E501
        'show_progress_grid': 'show_progress_grid',  # noqa: E501
        'show_progress_every_n_steps': 'show_progress_every_n_steps',  # noqa: E501
        'show_progress_type': 'show_progress_type',  # noqa: E501
        'live_preview_content': 'live_preview_content',  # noqa: E501
        'live_preview_refresh_period': 'live_preview_refresh_period',  # noqa: E501
        'hide_samplers': 'hide_samplers',  # noqa: E501
        'eta_ddim': 'eta_ddim',  # noqa: E501
        'eta_ancestral': 'eta_ancestral',  # noqa: E501
        'ddim_discretize': 'ddim_discretize',  # noqa: E501
        's_churn': 's_churn',  # noqa: E501
        's_tmin': 's_tmin',  # noqa: E501
        's_noise': 's_noise',  # noqa: E501
        'eta_noise_seed_delta': 'eta_noise_seed_delta',  # noqa: E501
        'always_discard_next_to_last_sigma': 'always_discard_next_to_last_sigma',  # noqa: E501
        'uni_pc_variant': 'uni_pc_variant',  # noqa: E501
        'uni_pc_skip_type': 'uni_pc_skip_type',  # noqa: E501
        'uni_pc_order': 'uni_pc_order',  # noqa: E501
        'uni_pc_lower_order_final': 'uni_pc_lower_order_final',  # noqa: E501
        'postprocessing_enable_in_main_ui': 'postprocessing_enable_in_main_ui',  # noqa: E501
        'postprocessing_operation_order': 'postprocessing_operation_order',  # noqa: E501
        'upscaling_max_images_in_cache': 'upscaling_max_images_in_cache',  # noqa: E501
        'disabled_extensions': 'disabled_extensions',  # noqa: E501
        'disable_all_extensions': 'disable_all_extensions',  # noqa: E501
        'sd_checkpoint_hash': 'sd_checkpoint_hash',  # noqa: E501
        'sd_lyco': 'sd_lyco',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Options - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            samples_save (bool): Always save all generated images. [optional] if omitted the server will use the default value of True  # noqa: E501
            samples_format (str): File format for images. [optional] if omitted the server will use the default value of "png"  # noqa: E501
            samples_filename_pattern (str): Images filename pattern. [optional] if omitted the server will use the default value of ""  # noqa: E501
            save_images_add_number (bool): Add number to filename when saving. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_save (bool): Always save all generated image grids. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_format (str): File format for grids. [optional] if omitted the server will use the default value of "png"  # noqa: E501
            grid_extended_filename (bool): Add extended info (seed, prompt) to filename when saving grid. [optional] if omitted the server will use the default value of False  # noqa: E501
            grid_only_if_multiple (bool): Do not save grids consisting of one picture. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_prevent_empty_spots (bool): Prevent empty spots in grid (when set to autodetect). [optional] if omitted the server will use the default value of False  # noqa: E501
            n_rows (float): Grid row count; use -1 for autodetect and 0 for it to be same as batch size. [optional] if omitted the server will use the default value of -1  # noqa: E501
            enable_pnginfo (bool): Save text information about generation parameters as chunks to png files. [optional] if omitted the server will use the default value of True  # noqa: E501
            save_txt (bool): Create a text file next to every image with generation parameters.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_images_before_face_restoration (bool): Save a copy of image before doing face restoration.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_images_before_highres_fix (bool): Save a copy of image before applying highres fix.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_images_before_color_correction (bool): Save a copy of image before applying color correction to img2img results. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_mask (bool): For inpainting, save a copy of the greyscale mask. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_mask_composite (bool): For inpainting, save a masked composite. [optional] if omitted the server will use the default value of False  # noqa: E501
            jpeg_quality (float): Quality for saved jpeg images. [optional] if omitted the server will use the default value of 80  # noqa: E501
            webp_lossless (bool): Use lossless compression for webp images. [optional] if omitted the server will use the default value of False  # noqa: E501
            export_for_4chan (bool): If the saved image file size is above the limit, or its either width or height are above the limit, save a downscaled copy as JPG. [optional] if omitted the server will use the default value of True  # noqa: E501
            img_downscale_threshold (float): File size limit for the above option, MB. [optional] if omitted the server will use the default value of 4.0  # noqa: E501
            target_side_length (float): Width/height limit for the above option, in pixels. [optional] if omitted the server will use the default value of 4000  # noqa: E501
            img_max_size_mp (float): Maximum image size, in megapixels. [optional] if omitted the server will use the default value of 200  # noqa: E501
            use_original_name_batch (bool): Use original name for output filename during batch process in extras tab. [optional] if omitted the server will use the default value of True  # noqa: E501
            use_upscaler_name_as_suffix (bool): Use upscaler name as filename suffix in the extras tab. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_selected_only (bool): When using 'Save' button, only save a single selected image. [optional] if omitted the server will use the default value of True  # noqa: E501
            do_not_add_watermark (bool): Do not add watermark to images. [optional] if omitted the server will use the default value of False  # noqa: E501
            temp_dir (str): Directory for temporary images; leave empty for default. [optional] if omitted the server will use the default value of ""  # noqa: E501
            clean_temp_dir_at_start (bool): Cleanup non-default temporary directory when starting webui. [optional] if omitted the server will use the default value of False  # noqa: E501
            outdir_samples (str): Output directory for images; if empty, defaults to three directories below. [optional] if omitted the server will use the default value of ""  # noqa: E501
            outdir_txt2img_samples (str): Output directory for txt2img images. [optional] if omitted the server will use the default value of "outputs/txt2img-images"  # noqa: E501
            outdir_img2img_samples (str): Output directory for img2img images. [optional] if omitted the server will use the default value of "outputs/img2img-images"  # noqa: E501
            outdir_extras_samples (str): Output directory for images from extras tab. [optional] if omitted the server will use the default value of "outputs/extras-images"  # noqa: E501
            outdir_grids (str): Output directory for grids; if empty, defaults to two directories below. [optional] if omitted the server will use the default value of ""  # noqa: E501
            outdir_txt2img_grids (str): Output directory for txt2img grids. [optional] if omitted the server will use the default value of "outputs/txt2img-grids"  # noqa: E501
            outdir_img2img_grids (str): Output directory for img2img grids. [optional] if omitted the server will use the default value of "outputs/img2img-grids"  # noqa: E501
            outdir_save (str): Directory for saving images using the Save button. [optional] if omitted the server will use the default value of "log/images"  # noqa: E501
            save_to_dirs (bool): Save images to a subdirectory. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_save_to_dirs (bool): Save grids to a subdirectory. [optional] if omitted the server will use the default value of True  # noqa: E501
            use_save_to_dirs_for_ui (bool): When using \"Save\" button, save images to a subdirectory. [optional] if omitted the server will use the default value of False  # noqa: E501
            directories_filename_pattern (str): Directory name pattern. [optional] if omitted the server will use the default value of "[date]"  # noqa: E501
            directories_max_prompt_words (float): Max prompt words for [prompt_words] pattern. [optional] if omitted the server will use the default value of 8  # noqa: E501
            esrgan_tile (float): Tile size for ESRGAN upscalers. 0 = no tiling.. [optional] if omitted the server will use the default value of 192  # noqa: E501
            esrgan_tile_overlap (float): Tile overlap, in pixels for ESRGAN upscalers. Low values = visible seam.. [optional] if omitted the server will use the default value of 8  # noqa: E501
            realesrgan_enabled_models ([bool, date, datetime, dict, float, int, list, str, none_type]): Select which Real-ESRGAN models to show in the web UI. (Requires restart). [optional] if omitted the server will use the default value of ["R-ESRGAN 4x+","R-ESRGAN 4x+ Anime6B"]  # noqa: E501
            upscaler_for_img2img (none_type): Upscaler for img2img. [optional]  # noqa: E501
            face_restoration_model (str): Face restoration model. [optional] if omitted the server will use the default value of "CodeFormer"  # noqa: E501
            code_former_weight (float): CodeFormer weight parameter; 0 = maximum effect; 1 = minimum effect. [optional] if omitted the server will use the default value of 0.5  # noqa: E501
            face_restoration_unload (bool): Move face restoration model from VRAM into RAM after processing. [optional] if omitted the server will use the default value of False  # noqa: E501
            show_warnings (bool): Show warnings in console.. [optional] if omitted the server will use the default value of False  # noqa: E501
            memmon_poll_rate (float): VRAM usage polls per second during generation. Set to 0 to disable.. [optional] if omitted the server will use the default value of 8  # noqa: E501
            samples_log_stdout (bool): Always print all generation info to standard output. [optional] if omitted the server will use the default value of False  # noqa: E501
            multiple_tqdm (bool): Add a second progress bar to the console that shows progress for an entire job.. [optional] if omitted the server will use the default value of True  # noqa: E501
            print_hypernet_extra (bool): Print extra hypernetwork information to console.. [optional] if omitted the server will use the default value of False  # noqa: E501
            unload_models_when_training (bool): Move VAE and CLIP to RAM when training if possible. Saves VRAM.. [optional] if omitted the server will use the default value of False  # noqa: E501
            pin_memory (bool): Turn on pin_memory for DataLoader. Makes training slightly faster but can increase memory usage.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_optimizer_state (bool): Saves Optimizer state as separate *.optim file. Training of embedding or HN can be resumed with the matching optim file.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_training_settings_to_txt (bool): Save textual inversion and hypernet settings to a text file whenever training starts.. [optional] if omitted the server will use the default value of True  # noqa: E501
            dataset_filename_word_regex (str): Filename word regex. [optional] if omitted the server will use the default value of ""  # noqa: E501
            dataset_filename_join_string (str): Filename join string. [optional] if omitted the server will use the default value of " "  # noqa: E501
            training_image_repeats_per_epoch (float): Number of repeats for a single input image per epoch; used only for displaying epoch number. [optional] if omitted the server will use the default value of 1  # noqa: E501
            training_write_csv_every (float): Save an csv containing the loss to log directory every N steps, 0 to disable. [optional] if omitted the server will use the default value of 500  # noqa: E501
            training_xattention_optimizations (bool): Use cross attention optimizations while training. [optional] if omitted the server will use the default value of False  # noqa: E501
            training_enable_tensorboard (bool): Enable tensorboard logging.. [optional] if omitted the server will use the default value of False  # noqa: E501
            training_tensorboard_save_images (bool): Save generated images within tensorboard.. [optional] if omitted the server will use the default value of False  # noqa: E501
            training_tensorboard_flush_every (float): How often, in seconds, to flush the pending tensorboard events and summaries to disk.. [optional] if omitted the server will use the default value of 120  # noqa: E501
            sd_model_checkpoint (str): Stable Diffusion checkpoint. [optional]  # noqa: E501
            sd_checkpoint_cache (float): Checkpoints to cache in RAM. [optional] if omitted the server will use the default value of 0  # noqa: E501
            sd_vae_checkpoint_cache (float): VAE Checkpoints to cache in RAM. [optional] if omitted the server will use the default value of 0  # noqa: E501
            sd_vae (str): SD VAE. [optional] if omitted the server will use the default value of "Automatic"  # noqa: E501
            sd_vae_as_default (bool): Ignore selected VAE for stable diffusion checkpoints that have their own .vae.pt next to them. [optional] if omitted the server will use the default value of True  # noqa: E501
            inpainting_mask_weight (float): Inpainting conditioning mask strength. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            initial_noise_multiplier (float): Noise multiplier for img2img. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            img2img_color_correction (bool): Apply color correction to img2img results to match original colors.. [optional] if omitted the server will use the default value of False  # noqa: E501
            img2img_fix_steps (bool): With img2img, do exactly the amount of steps the slider specifies (normally you'd do less with less denoising).. [optional] if omitted the server will use the default value of False  # noqa: E501
            img2img_background_color (str): With img2img, fill image's transparent parts with this color.. [optional] if omitted the server will use the default value of "#ffffff"  # noqa: E501
            enable_quantization (bool): Enable quantization in K samplers for sharper and cleaner results. This may change existing seeds. Requires restart to apply.. [optional] if omitted the server will use the default value of False  # noqa: E501
            enable_emphasis (bool): Emphasis: use (text) to make model pay more attention to text and [text] to make it pay less attention. [optional] if omitted the server will use the default value of True  # noqa: E501
            enable_batch_seeds (bool): Make K-diffusion samplers produce same images in a batch as when making a single image. [optional] if omitted the server will use the default value of True  # noqa: E501
            comma_padding_backtrack (float): Increase coherency by padding from the last comma within n tokens when using more than 75 tokens. [optional] if omitted the server will use the default value of 20  # noqa: E501
            clip_stop_at_last_layers (float): Clip skip. [optional] if omitted the server will use the default value of 1  # noqa: E501
            upcast_attn (bool): Upcast cross attention layer to float32. [optional] if omitted the server will use the default value of False  # noqa: E501
            use_old_emphasis_implementation (bool): Use old emphasis implementation. Can be useful to reproduce old seeds.. [optional] if omitted the server will use the default value of False  # noqa: E501
            use_old_karras_scheduler_sigmas (bool): Use old karras scheduler sigmas (0.1 to 10).. [optional] if omitted the server will use the default value of False  # noqa: E501
            no_dpmpp_sde_batch_determinism (bool): Do not make DPM++ SDE deterministic across different batch sizes.. [optional] if omitted the server will use the default value of False  # noqa: E501
            use_old_hires_fix_width_height (bool): For hires fix, use width/height sliders to set final resolution rather than first pass (disables Upscale by, Resize width/height to).. [optional] if omitted the server will use the default value of False  # noqa: E501
            interrogate_keep_models_in_memory (bool): Interrogate: keep models in VRAM. [optional] if omitted the server will use the default value of False  # noqa: E501
            interrogate_return_ranks (bool): Interrogate: include ranks of model tags matches in results (Has no effect on caption-based interrogators).. [optional] if omitted the server will use the default value of False  # noqa: E501
            interrogate_clip_num_beams (float): Interrogate: num_beams for BLIP. [optional] if omitted the server will use the default value of 1  # noqa: E501
            interrogate_clip_min_length (float): Interrogate: minimum description length (excluding artists, etc..). [optional] if omitted the server will use the default value of 24  # noqa: E501
            interrogate_clip_max_length (float): Interrogate: maximum description length. [optional] if omitted the server will use the default value of 48  # noqa: E501
            interrogate_clip_dict_limit (float): CLIP: maximum number of lines in text file (0 = No limit). [optional] if omitted the server will use the default value of 1500  # noqa: E501
            interrogate_clip_skip_categories ([bool, date, datetime, dict, float, int, list, str, none_type]): CLIP: skip inquire categories. [optional] if omitted the server will use the default value of []  # noqa: E501
            interrogate_deepbooru_score_threshold (float): Interrogate: deepbooru score threshold. [optional] if omitted the server will use the default value of 0.5  # noqa: E501
            deepbooru_sort_alpha (bool): Interrogate: deepbooru sort alphabetically. [optional] if omitted the server will use the default value of True  # noqa: E501
            deepbooru_use_spaces (bool): use spaces for tags in deepbooru. [optional] if omitted the server will use the default value of False  # noqa: E501
            deepbooru_escape (bool): escape (\\) brackets in deepbooru (so they are used as literal brackets and not for emphasis). [optional] if omitted the server will use the default value of True  # noqa: E501
            deepbooru_filter_tags (str): filter out those tags from deepbooru output (separated by comma). [optional] if omitted the server will use the default value of ""  # noqa: E501
            extra_networks_default_view (str): Default view for Extra Networks. [optional] if omitted the server will use the default value of "cards"  # noqa: E501
            extra_networks_default_multiplier (float): Multiplier for extra networks. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            extra_networks_card_width (float): Card width for Extra Networks (px). [optional] if omitted the server will use the default value of 0  # noqa: E501
            extra_networks_card_height (float): Card height for Extra Networks (px). [optional] if omitted the server will use the default value of 0  # noqa: E501
            extra_networks_add_text_separator (str): Extra text to add before <...> when adding extra network to prompt. [optional] if omitted the server will use the default value of " "  # noqa: E501
            sd_hypernetwork (str): Add hypernetwork to prompt. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            return_grid (bool): Show grid in results for web. [optional] if omitted the server will use the default value of True  # noqa: E501
            return_mask (bool): For inpainting, include the greyscale mask in results for web. [optional] if omitted the server will use the default value of False  # noqa: E501
            return_mask_composite (bool): For inpainting, include masked composite in results for web. [optional] if omitted the server will use the default value of False  # noqa: E501
            do_not_show_images (bool): Do not show any images in results for web. [optional] if omitted the server will use the default value of False  # noqa: E501
            add_model_hash_to_info (bool): Add model hash to generation information. [optional] if omitted the server will use the default value of True  # noqa: E501
            add_model_name_to_info (bool): Add model name to generation information. [optional] if omitted the server will use the default value of True  # noqa: E501
            disable_weights_auto_swap (bool): When reading generation parameters from text into UI (from PNG info or pasted text), do not change the selected model/checkpoint.. [optional] if omitted the server will use the default value of True  # noqa: E501
            send_seed (bool): Send seed when sending prompt or image to other interface. [optional] if omitted the server will use the default value of True  # noqa: E501
            send_size (bool): Send size when sending prompt or image to another interface. [optional] if omitted the server will use the default value of True  # noqa: E501
            font (str): Font for image grids that have text. [optional] if omitted the server will use the default value of ""  # noqa: E501
            js_modal_lightbox (bool): Enable full page image viewer. [optional] if omitted the server will use the default value of True  # noqa: E501
            js_modal_lightbox_initially_zoomed (bool): Show images zoomed in by default in full page image viewer. [optional] if omitted the server will use the default value of True  # noqa: E501
            show_progress_in_title (bool): Show generation progress in window title.. [optional] if omitted the server will use the default value of True  # noqa: E501
            samplers_in_dropdown (bool): Use dropdown for sampler selection instead of radio group. [optional] if omitted the server will use the default value of True  # noqa: E501
            dimensions_and_batch_together (bool): Show Width/Height and Batch sliders in same row. [optional] if omitted the server will use the default value of True  # noqa: E501
            keyedit_precision_attention (float): Ctrl+up/down precision when editing (attention:1.1). [optional] if omitted the server will use the default value of 0.1  # noqa: E501
            keyedit_precision_extra (float): Ctrl+up/down precision when editing <extra networks:0.9>. [optional] if omitted the server will use the default value of 0.05  # noqa: E501
            quicksettings (str): Quicksettings list. [optional] if omitted the server will use the default value of "sd_model_checkpoint"  # noqa: E501
            hidden_tabs ([bool, date, datetime, dict, float, int, list, str, none_type]): Hidden UI tabs (requires restart). [optional] if omitted the server will use the default value of []  # noqa: E501
            ui_reorder (str): txt2img/img2img UI item order. [optional] if omitted the server will use the default value of "inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts"  # noqa: E501
            ui_extra_networks_tab_reorder (str): Extra networks tab order. [optional] if omitted the server will use the default value of ""  # noqa: E501
            localization (str): Localization (requires restart). [optional] if omitted the server will use the default value of "None"  # noqa: E501
            show_progressbar (bool): Show progressbar. [optional] if omitted the server will use the default value of True  # noqa: E501
            live_previews_enable (bool): Show live previews of the created image. [optional] if omitted the server will use the default value of True  # noqa: E501
            show_progress_grid (bool): Show previews of all images generated in a batch as a grid. [optional] if omitted the server will use the default value of True  # noqa: E501
            show_progress_every_n_steps (float): Show new live preview image every N sampling steps. Set to -1 to show after completion of batch.. [optional] if omitted the server will use the default value of 10  # noqa: E501
            show_progress_type (str): Image creation progress preview mode. [optional] if omitted the server will use the default value of "Approx NN"  # noqa: E501
            live_preview_content (str): Live preview subject. [optional] if omitted the server will use the default value of "Prompt"  # noqa: E501
            live_preview_refresh_period (float): Progressbar/preview update period, in milliseconds. [optional] if omitted the server will use the default value of 1000  # noqa: E501
            hide_samplers ([bool, date, datetime, dict, float, int, list, str, none_type]): Hide samplers in user interface (requires restart). [optional] if omitted the server will use the default value of []  # noqa: E501
            eta_ddim (float): eta (noise multiplier) for DDIM. [optional] if omitted the server will use the default value of 0.0  # noqa: E501
            eta_ancestral (float): eta (noise multiplier) for ancestral samplers. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            ddim_discretize (str): img2img DDIM discretize. [optional] if omitted the server will use the default value of "uniform"  # noqa: E501
            s_churn (float): sigma churn. [optional] if omitted the server will use the default value of 0.0  # noqa: E501
            s_tmin (float): sigma tmin. [optional] if omitted the server will use the default value of 0.0  # noqa: E501
            s_noise (float): sigma noise. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            eta_noise_seed_delta (float): Eta noise seed delta. [optional] if omitted the server will use the default value of 0  # noqa: E501
            always_discard_next_to_last_sigma (bool): Always discard next-to-last sigma. [optional] if omitted the server will use the default value of False  # noqa: E501
            uni_pc_variant (str): UniPC variant. [optional] if omitted the server will use the default value of "bh1"  # noqa: E501
            uni_pc_skip_type (str): UniPC skip type. [optional] if omitted the server will use the default value of "time_uniform"  # noqa: E501
            uni_pc_order (float): UniPC order (must be < sampling steps). [optional] if omitted the server will use the default value of 3  # noqa: E501
            uni_pc_lower_order_final (bool): UniPC lower order final. [optional] if omitted the server will use the default value of True  # noqa: E501
            postprocessing_enable_in_main_ui ([bool, date, datetime, dict, float, int, list, str, none_type]): Enable postprocessing operations in txt2img and img2img tabs. [optional] if omitted the server will use the default value of []  # noqa: E501
            postprocessing_operation_order ([bool, date, datetime, dict, float, int, list, str, none_type]): Postprocessing operation order. [optional] if omitted the server will use the default value of []  # noqa: E501
            upscaling_max_images_in_cache (float): Maximum number of images in upscaling cache. [optional] if omitted the server will use the default value of 5  # noqa: E501
            disabled_extensions ([bool, date, datetime, dict, float, int, list, str, none_type]): Disable these extensions. [optional] if omitted the server will use the default value of []  # noqa: E501
            disable_all_extensions (str): Disable all extensions (preserves the list of disabled extensions). [optional] if omitted the server will use the default value of "none"  # noqa: E501
            sd_checkpoint_hash (str): SHA256 hash of the current checkpoint. [optional] if omitted the server will use the default value of ""  # noqa: E501
            sd_lyco (str): Add LyCORIS to prompt. [optional] if omitted the server will use the default value of "None"  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Options - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            samples_save (bool): Always save all generated images. [optional] if omitted the server will use the default value of True  # noqa: E501
            samples_format (str): File format for images. [optional] if omitted the server will use the default value of "png"  # noqa: E501
            samples_filename_pattern (str): Images filename pattern. [optional] if omitted the server will use the default value of ""  # noqa: E501
            save_images_add_number (bool): Add number to filename when saving. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_save (bool): Always save all generated image grids. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_format (str): File format for grids. [optional] if omitted the server will use the default value of "png"  # noqa: E501
            grid_extended_filename (bool): Add extended info (seed, prompt) to filename when saving grid. [optional] if omitted the server will use the default value of False  # noqa: E501
            grid_only_if_multiple (bool): Do not save grids consisting of one picture. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_prevent_empty_spots (bool): Prevent empty spots in grid (when set to autodetect). [optional] if omitted the server will use the default value of False  # noqa: E501
            n_rows (float): Grid row count; use -1 for autodetect and 0 for it to be same as batch size. [optional] if omitted the server will use the default value of -1  # noqa: E501
            enable_pnginfo (bool): Save text information about generation parameters as chunks to png files. [optional] if omitted the server will use the default value of True  # noqa: E501
            save_txt (bool): Create a text file next to every image with generation parameters.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_images_before_face_restoration (bool): Save a copy of image before doing face restoration.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_images_before_highres_fix (bool): Save a copy of image before applying highres fix.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_images_before_color_correction (bool): Save a copy of image before applying color correction to img2img results. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_mask (bool): For inpainting, save a copy of the greyscale mask. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_mask_composite (bool): For inpainting, save a masked composite. [optional] if omitted the server will use the default value of False  # noqa: E501
            jpeg_quality (float): Quality for saved jpeg images. [optional] if omitted the server will use the default value of 80  # noqa: E501
            webp_lossless (bool): Use lossless compression for webp images. [optional] if omitted the server will use the default value of False  # noqa: E501
            export_for_4chan (bool): If the saved image file size is above the limit, or its either width or height are above the limit, save a downscaled copy as JPG. [optional] if omitted the server will use the default value of True  # noqa: E501
            img_downscale_threshold (float): File size limit for the above option, MB. [optional] if omitted the server will use the default value of 4.0  # noqa: E501
            target_side_length (float): Width/height limit for the above option, in pixels. [optional] if omitted the server will use the default value of 4000  # noqa: E501
            img_max_size_mp (float): Maximum image size, in megapixels. [optional] if omitted the server will use the default value of 200  # noqa: E501
            use_original_name_batch (bool): Use original name for output filename during batch process in extras tab. [optional] if omitted the server will use the default value of True  # noqa: E501
            use_upscaler_name_as_suffix (bool): Use upscaler name as filename suffix in the extras tab. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_selected_only (bool): When using 'Save' button, only save a single selected image. [optional] if omitted the server will use the default value of True  # noqa: E501
            do_not_add_watermark (bool): Do not add watermark to images. [optional] if omitted the server will use the default value of False  # noqa: E501
            temp_dir (str): Directory for temporary images; leave empty for default. [optional] if omitted the server will use the default value of ""  # noqa: E501
            clean_temp_dir_at_start (bool): Cleanup non-default temporary directory when starting webui. [optional] if omitted the server will use the default value of False  # noqa: E501
            outdir_samples (str): Output directory for images; if empty, defaults to three directories below. [optional] if omitted the server will use the default value of ""  # noqa: E501
            outdir_txt2img_samples (str): Output directory for txt2img images. [optional] if omitted the server will use the default value of "outputs/txt2img-images"  # noqa: E501
            outdir_img2img_samples (str): Output directory for img2img images. [optional] if omitted the server will use the default value of "outputs/img2img-images"  # noqa: E501
            outdir_extras_samples (str): Output directory for images from extras tab. [optional] if omitted the server will use the default value of "outputs/extras-images"  # noqa: E501
            outdir_grids (str): Output directory for grids; if empty, defaults to two directories below. [optional] if omitted the server will use the default value of ""  # noqa: E501
            outdir_txt2img_grids (str): Output directory for txt2img grids. [optional] if omitted the server will use the default value of "outputs/txt2img-grids"  # noqa: E501
            outdir_img2img_grids (str): Output directory for img2img grids. [optional] if omitted the server will use the default value of "outputs/img2img-grids"  # noqa: E501
            outdir_save (str): Directory for saving images using the Save button. [optional] if omitted the server will use the default value of "log/images"  # noqa: E501
            save_to_dirs (bool): Save images to a subdirectory. [optional] if omitted the server will use the default value of True  # noqa: E501
            grid_save_to_dirs (bool): Save grids to a subdirectory. [optional] if omitted the server will use the default value of True  # noqa: E501
            use_save_to_dirs_for_ui (bool): When using \"Save\" button, save images to a subdirectory. [optional] if omitted the server will use the default value of False  # noqa: E501
            directories_filename_pattern (str): Directory name pattern. [optional] if omitted the server will use the default value of "[date]"  # noqa: E501
            directories_max_prompt_words (float): Max prompt words for [prompt_words] pattern. [optional] if omitted the server will use the default value of 8  # noqa: E501
            esrgan_tile (float): Tile size for ESRGAN upscalers. 0 = no tiling.. [optional] if omitted the server will use the default value of 192  # noqa: E501
            esrgan_tile_overlap (float): Tile overlap, in pixels for ESRGAN upscalers. Low values = visible seam.. [optional] if omitted the server will use the default value of 8  # noqa: E501
            realesrgan_enabled_models ([bool, date, datetime, dict, float, int, list, str, none_type]): Select which Real-ESRGAN models to show in the web UI. (Requires restart). [optional] if omitted the server will use the default value of ["R-ESRGAN 4x+","R-ESRGAN 4x+ Anime6B"]  # noqa: E501
            upscaler_for_img2img (none_type): Upscaler for img2img. [optional]  # noqa: E501
            face_restoration_model (str): Face restoration model. [optional] if omitted the server will use the default value of "CodeFormer"  # noqa: E501
            code_former_weight (float): CodeFormer weight parameter; 0 = maximum effect; 1 = minimum effect. [optional] if omitted the server will use the default value of 0.5  # noqa: E501
            face_restoration_unload (bool): Move face restoration model from VRAM into RAM after processing. [optional] if omitted the server will use the default value of False  # noqa: E501
            show_warnings (bool): Show warnings in console.. [optional] if omitted the server will use the default value of False  # noqa: E501
            memmon_poll_rate (float): VRAM usage polls per second during generation. Set to 0 to disable.. [optional] if omitted the server will use the default value of 8  # noqa: E501
            samples_log_stdout (bool): Always print all generation info to standard output. [optional] if omitted the server will use the default value of False  # noqa: E501
            multiple_tqdm (bool): Add a second progress bar to the console that shows progress for an entire job.. [optional] if omitted the server will use the default value of True  # noqa: E501
            print_hypernet_extra (bool): Print extra hypernetwork information to console.. [optional] if omitted the server will use the default value of False  # noqa: E501
            unload_models_when_training (bool): Move VAE and CLIP to RAM when training if possible. Saves VRAM.. [optional] if omitted the server will use the default value of False  # noqa: E501
            pin_memory (bool): Turn on pin_memory for DataLoader. Makes training slightly faster but can increase memory usage.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_optimizer_state (bool): Saves Optimizer state as separate *.optim file. Training of embedding or HN can be resumed with the matching optim file.. [optional] if omitted the server will use the default value of False  # noqa: E501
            save_training_settings_to_txt (bool): Save textual inversion and hypernet settings to a text file whenever training starts.. [optional] if omitted the server will use the default value of True  # noqa: E501
            dataset_filename_word_regex (str): Filename word regex. [optional] if omitted the server will use the default value of ""  # noqa: E501
            dataset_filename_join_string (str): Filename join string. [optional] if omitted the server will use the default value of " "  # noqa: E501
            training_image_repeats_per_epoch (float): Number of repeats for a single input image per epoch; used only for displaying epoch number. [optional] if omitted the server will use the default value of 1  # noqa: E501
            training_write_csv_every (float): Save an csv containing the loss to log directory every N steps, 0 to disable. [optional] if omitted the server will use the default value of 500  # noqa: E501
            training_xattention_optimizations (bool): Use cross attention optimizations while training. [optional] if omitted the server will use the default value of False  # noqa: E501
            training_enable_tensorboard (bool): Enable tensorboard logging.. [optional] if omitted the server will use the default value of False  # noqa: E501
            training_tensorboard_save_images (bool): Save generated images within tensorboard.. [optional] if omitted the server will use the default value of False  # noqa: E501
            training_tensorboard_flush_every (float): How often, in seconds, to flush the pending tensorboard events and summaries to disk.. [optional] if omitted the server will use the default value of 120  # noqa: E501
            sd_model_checkpoint (str): Stable Diffusion checkpoint. [optional]  # noqa: E501
            sd_checkpoint_cache (float): Checkpoints to cache in RAM. [optional] if omitted the server will use the default value of 0  # noqa: E501
            sd_vae_checkpoint_cache (float): VAE Checkpoints to cache in RAM. [optional] if omitted the server will use the default value of 0  # noqa: E501
            sd_vae (str): SD VAE. [optional] if omitted the server will use the default value of "Automatic"  # noqa: E501
            sd_vae_as_default (bool): Ignore selected VAE for stable diffusion checkpoints that have their own .vae.pt next to them. [optional] if omitted the server will use the default value of True  # noqa: E501
            inpainting_mask_weight (float): Inpainting conditioning mask strength. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            initial_noise_multiplier (float): Noise multiplier for img2img. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            img2img_color_correction (bool): Apply color correction to img2img results to match original colors.. [optional] if omitted the server will use the default value of False  # noqa: E501
            img2img_fix_steps (bool): With img2img, do exactly the amount of steps the slider specifies (normally you'd do less with less denoising).. [optional] if omitted the server will use the default value of False  # noqa: E501
            img2img_background_color (str): With img2img, fill image's transparent parts with this color.. [optional] if omitted the server will use the default value of "#ffffff"  # noqa: E501
            enable_quantization (bool): Enable quantization in K samplers for sharper and cleaner results. This may change existing seeds. Requires restart to apply.. [optional] if omitted the server will use the default value of False  # noqa: E501
            enable_emphasis (bool): Emphasis: use (text) to make model pay more attention to text and [text] to make it pay less attention. [optional] if omitted the server will use the default value of True  # noqa: E501
            enable_batch_seeds (bool): Make K-diffusion samplers produce same images in a batch as when making a single image. [optional] if omitted the server will use the default value of True  # noqa: E501
            comma_padding_backtrack (float): Increase coherency by padding from the last comma within n tokens when using more than 75 tokens. [optional] if omitted the server will use the default value of 20  # noqa: E501
            clip_stop_at_last_layers (float): Clip skip. [optional] if omitted the server will use the default value of 1  # noqa: E501
            upcast_attn (bool): Upcast cross attention layer to float32. [optional] if omitted the server will use the default value of False  # noqa: E501
            use_old_emphasis_implementation (bool): Use old emphasis implementation. Can be useful to reproduce old seeds.. [optional] if omitted the server will use the default value of False  # noqa: E501
            use_old_karras_scheduler_sigmas (bool): Use old karras scheduler sigmas (0.1 to 10).. [optional] if omitted the server will use the default value of False  # noqa: E501
            no_dpmpp_sde_batch_determinism (bool): Do not make DPM++ SDE deterministic across different batch sizes.. [optional] if omitted the server will use the default value of False  # noqa: E501
            use_old_hires_fix_width_height (bool): For hires fix, use width/height sliders to set final resolution rather than first pass (disables Upscale by, Resize width/height to).. [optional] if omitted the server will use the default value of False  # noqa: E501
            interrogate_keep_models_in_memory (bool): Interrogate: keep models in VRAM. [optional] if omitted the server will use the default value of False  # noqa: E501
            interrogate_return_ranks (bool): Interrogate: include ranks of model tags matches in results (Has no effect on caption-based interrogators).. [optional] if omitted the server will use the default value of False  # noqa: E501
            interrogate_clip_num_beams (float): Interrogate: num_beams for BLIP. [optional] if omitted the server will use the default value of 1  # noqa: E501
            interrogate_clip_min_length (float): Interrogate: minimum description length (excluding artists, etc..). [optional] if omitted the server will use the default value of 24  # noqa: E501
            interrogate_clip_max_length (float): Interrogate: maximum description length. [optional] if omitted the server will use the default value of 48  # noqa: E501
            interrogate_clip_dict_limit (float): CLIP: maximum number of lines in text file (0 = No limit). [optional] if omitted the server will use the default value of 1500  # noqa: E501
            interrogate_clip_skip_categories ([bool, date, datetime, dict, float, int, list, str, none_type]): CLIP: skip inquire categories. [optional] if omitted the server will use the default value of []  # noqa: E501
            interrogate_deepbooru_score_threshold (float): Interrogate: deepbooru score threshold. [optional] if omitted the server will use the default value of 0.5  # noqa: E501
            deepbooru_sort_alpha (bool): Interrogate: deepbooru sort alphabetically. [optional] if omitted the server will use the default value of True  # noqa: E501
            deepbooru_use_spaces (bool): use spaces for tags in deepbooru. [optional] if omitted the server will use the default value of False  # noqa: E501
            deepbooru_escape (bool): escape (\\) brackets in deepbooru (so they are used as literal brackets and not for emphasis). [optional] if omitted the server will use the default value of True  # noqa: E501
            deepbooru_filter_tags (str): filter out those tags from deepbooru output (separated by comma). [optional] if omitted the server will use the default value of ""  # noqa: E501
            extra_networks_default_view (str): Default view for Extra Networks. [optional] if omitted the server will use the default value of "cards"  # noqa: E501
            extra_networks_default_multiplier (float): Multiplier for extra networks. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            extra_networks_card_width (float): Card width for Extra Networks (px). [optional] if omitted the server will use the default value of 0  # noqa: E501
            extra_networks_card_height (float): Card height for Extra Networks (px). [optional] if omitted the server will use the default value of 0  # noqa: E501
            extra_networks_add_text_separator (str): Extra text to add before <...> when adding extra network to prompt. [optional] if omitted the server will use the default value of " "  # noqa: E501
            sd_hypernetwork (str): Add hypernetwork to prompt. [optional] if omitted the server will use the default value of "None"  # noqa: E501
            return_grid (bool): Show grid in results for web. [optional] if omitted the server will use the default value of True  # noqa: E501
            return_mask (bool): For inpainting, include the greyscale mask in results for web. [optional] if omitted the server will use the default value of False  # noqa: E501
            return_mask_composite (bool): For inpainting, include masked composite in results for web. [optional] if omitted the server will use the default value of False  # noqa: E501
            do_not_show_images (bool): Do not show any images in results for web. [optional] if omitted the server will use the default value of False  # noqa: E501
            add_model_hash_to_info (bool): Add model hash to generation information. [optional] if omitted the server will use the default value of True  # noqa: E501
            add_model_name_to_info (bool): Add model name to generation information. [optional] if omitted the server will use the default value of True  # noqa: E501
            disable_weights_auto_swap (bool): When reading generation parameters from text into UI (from PNG info or pasted text), do not change the selected model/checkpoint.. [optional] if omitted the server will use the default value of True  # noqa: E501
            send_seed (bool): Send seed when sending prompt or image to other interface. [optional] if omitted the server will use the default value of True  # noqa: E501
            send_size (bool): Send size when sending prompt or image to another interface. [optional] if omitted the server will use the default value of True  # noqa: E501
            font (str): Font for image grids that have text. [optional] if omitted the server will use the default value of ""  # noqa: E501
            js_modal_lightbox (bool): Enable full page image viewer. [optional] if omitted the server will use the default value of True  # noqa: E501
            js_modal_lightbox_initially_zoomed (bool): Show images zoomed in by default in full page image viewer. [optional] if omitted the server will use the default value of True  # noqa: E501
            show_progress_in_title (bool): Show generation progress in window title.. [optional] if omitted the server will use the default value of True  # noqa: E501
            samplers_in_dropdown (bool): Use dropdown for sampler selection instead of radio group. [optional] if omitted the server will use the default value of True  # noqa: E501
            dimensions_and_batch_together (bool): Show Width/Height and Batch sliders in same row. [optional] if omitted the server will use the default value of True  # noqa: E501
            keyedit_precision_attention (float): Ctrl+up/down precision when editing (attention:1.1). [optional] if omitted the server will use the default value of 0.1  # noqa: E501
            keyedit_precision_extra (float): Ctrl+up/down precision when editing <extra networks:0.9>. [optional] if omitted the server will use the default value of 0.05  # noqa: E501
            quicksettings (str): Quicksettings list. [optional] if omitted the server will use the default value of "sd_model_checkpoint"  # noqa: E501
            hidden_tabs ([bool, date, datetime, dict, float, int, list, str, none_type]): Hidden UI tabs (requires restart). [optional] if omitted the server will use the default value of []  # noqa: E501
            ui_reorder (str): txt2img/img2img UI item order. [optional] if omitted the server will use the default value of "inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts"  # noqa: E501
            ui_extra_networks_tab_reorder (str): Extra networks tab order. [optional] if omitted the server will use the default value of ""  # noqa: E501
            localization (str): Localization (requires restart). [optional] if omitted the server will use the default value of "None"  # noqa: E501
            show_progressbar (bool): Show progressbar. [optional] if omitted the server will use the default value of True  # noqa: E501
            live_previews_enable (bool): Show live previews of the created image. [optional] if omitted the server will use the default value of True  # noqa: E501
            show_progress_grid (bool): Show previews of all images generated in a batch as a grid. [optional] if omitted the server will use the default value of True  # noqa: E501
            show_progress_every_n_steps (float): Show new live preview image every N sampling steps. Set to -1 to show after completion of batch.. [optional] if omitted the server will use the default value of 10  # noqa: E501
            show_progress_type (str): Image creation progress preview mode. [optional] if omitted the server will use the default value of "Approx NN"  # noqa: E501
            live_preview_content (str): Live preview subject. [optional] if omitted the server will use the default value of "Prompt"  # noqa: E501
            live_preview_refresh_period (float): Progressbar/preview update period, in milliseconds. [optional] if omitted the server will use the default value of 1000  # noqa: E501
            hide_samplers ([bool, date, datetime, dict, float, int, list, str, none_type]): Hide samplers in user interface (requires restart). [optional] if omitted the server will use the default value of []  # noqa: E501
            eta_ddim (float): eta (noise multiplier) for DDIM. [optional] if omitted the server will use the default value of 0.0  # noqa: E501
            eta_ancestral (float): eta (noise multiplier) for ancestral samplers. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            ddim_discretize (str): img2img DDIM discretize. [optional] if omitted the server will use the default value of "uniform"  # noqa: E501
            s_churn (float): sigma churn. [optional] if omitted the server will use the default value of 0.0  # noqa: E501
            s_tmin (float): sigma tmin. [optional] if omitted the server will use the default value of 0.0  # noqa: E501
            s_noise (float): sigma noise. [optional] if omitted the server will use the default value of 1.0  # noqa: E501
            eta_noise_seed_delta (float): Eta noise seed delta. [optional] if omitted the server will use the default value of 0  # noqa: E501
            always_discard_next_to_last_sigma (bool): Always discard next-to-last sigma. [optional] if omitted the server will use the default value of False  # noqa: E501
            uni_pc_variant (str): UniPC variant. [optional] if omitted the server will use the default value of "bh1"  # noqa: E501
            uni_pc_skip_type (str): UniPC skip type. [optional] if omitted the server will use the default value of "time_uniform"  # noqa: E501
            uni_pc_order (float): UniPC order (must be < sampling steps). [optional] if omitted the server will use the default value of 3  # noqa: E501
            uni_pc_lower_order_final (bool): UniPC lower order final. [optional] if omitted the server will use the default value of True  # noqa: E501
            postprocessing_enable_in_main_ui ([bool, date, datetime, dict, float, int, list, str, none_type]): Enable postprocessing operations in txt2img and img2img tabs. [optional] if omitted the server will use the default value of []  # noqa: E501
            postprocessing_operation_order ([bool, date, datetime, dict, float, int, list, str, none_type]): Postprocessing operation order. [optional] if omitted the server will use the default value of []  # noqa: E501
            upscaling_max_images_in_cache (float): Maximum number of images in upscaling cache. [optional] if omitted the server will use the default value of 5  # noqa: E501
            disabled_extensions ([bool, date, datetime, dict, float, int, list, str, none_type]): Disable these extensions. [optional] if omitted the server will use the default value of []  # noqa: E501
            disable_all_extensions (str): Disable all extensions (preserves the list of disabled extensions). [optional] if omitted the server will use the default value of "none"  # noqa: E501
            sd_checkpoint_hash (str): SHA256 hash of the current checkpoint. [optional] if omitted the server will use the default value of ""  # noqa: E501
            sd_lyco (str): Add LyCORIS to prompt. [optional] if omitted the server will use the default value of "None"  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
